api/urls.py
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('', views.api_urls, name='api_urls'),
    path('stock-list/', views.StockList, name='StockList'),
    path('stock-detail/<str:pk>/', views.StockDetail, name='stock-detail'),
    path('stock-create/', views.StockCreate, name='stock-create'),
    path('stock-update/<str:pk>/', views.StockUpdate, name='stock-update'),
    path('stock-delete/<str:pk>/', views.StockDelete, name='stock-delete')

    ]

sms_app/urls.py
from django.urls import path
from . import views


app_name = 'sms_app'
urlpatterns = [
    path('', views.all_stock, name='home'),
    path('stocks', views.all_stock, name='all_stock'),
    path('stock/<str:id>/', views.get_stock, name='get_stock'),
    path('receive_quantity/<str:id>/', views.receive_quantity, name='receive_quantity'),
    path('quantity_required/<str:id>/', views.quantity_required, name='quantity_required'),
    path('add/stock', views.add_stock, name='add_stock'),
    path('update/stock/<str:id>', views.update_stock, name='update_stock'),
    path('delete/stock/<str:id>', views.delete_stock, name='delete_stock'),
    path('reorder_level/<str:id>', views.reorder_level, name='reorder_level'),
    path('export-pdf', views.export_pdf, name='export-pdf'),
    path('export-excel', views.export_excel, name='export-excel'),
    # path('export-csv', views.export_csv, name='export-csv'),
    path('dashboard', views.dashboard, name='dashboard'),

]

stock_ms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sms.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock_ms_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sms_app.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = 'sms_app.views.error_404'
# handler500 = 'sms_app.views.error_500'
# handler403 = 'sms_app.views.error_403'
# handler400 = 'sms_app.views.error_400'

sms_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.name


category_choices = [('Furniture', 'Furniture'), ('Sport', 'Sport'),
                    ('Accessories Auto', 'Accessories Auto'), ('Movies', 'Movies')]


class Stock(models.Model):
    name = models.CharField(max_length=30, null=True, blank=True)
    description = models.TextField(default='', null=True, blank=True)
    price = models.IntegerField("Unit Price",null=True, blank=True)
    category = models.CharField('Category', max_length=40, blank=True, null=True, choices=category_choices)
    quantity_before = models.IntegerField(null=True, default=0, blank=True)
    quantity = models.IntegerField(null=True, default=0, blank=False)
    quantity_calc = models.IntegerField('Total Q', null=True, default=0, blank=True)
    image = models.ImageField(upload_to='sms_images/', blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    quantity_required = models.IntegerField('Q Required', blank=False, null=True)
    # user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    receive_quantity = models.IntegerField('Q Received', blank=False, null=True)
    receive_by = models.CharField(max_length=30, null=True, blank=True)
    issue_by = models.CharField(max_length=30, null=True, blank=True)
    issue_quantity = models.IntegerField(default=0, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    export_to_csv = models.BooleanField(default=False)
    reorder_level = models.IntegerField(default=0, null=True, blank=True)
    tags_id = models.ManyToManyField(Tag, blank=True)

# if you want to use calculated field you should remove field from form & its done

    def _get_quantity(self):
        return self.quantity
    quantity_before = property(_get_quantity)

    def _get_total_quantity(self):
        x = self.quantity + self.receive_quantity
        return x
    quantity_calc = property(_get_total_quantity)

    def _get_issue_by(self):
        return self.receive_by
    issue_by = property(_get_issue_by)

    def _get_issue_quantity(self):
        if self.quantity_required and self.receive_quantity:
            x = self.quantity_required - self.receive_quantity
            return x
    issue_quantity = property(_get_issue_quantity)

    def __str__(self):
        return self.name

sms_app/forms.py
from django import forms
from .models import Stock


class StockAdminFormView(forms.ModelForm):
    class Meta:
        model = Stock
        fields = "__all__"


class TagAdminFormView(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['name']


class StockFormView(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['name', 'description', 'category', 'price', 'quantity', 'receive_quantity', 'quantity_required',
                  'receive_by', 'image', 'tags_id', 'reorder_level']
        # fields = "__all__"


class StockUpdateForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['name', 'description', 'price', 'receive_quantity', 'quantity',
                  'receive_by', 'image', 'tags_id']


class StockSearchForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['name', 'quantity', 'export_to_csv']


class StockReceiveQuantityForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['receive_quantity']


class StockQuantityRequiredForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['quantity_required']


class ReorderLevelForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['reorder_level']

sms_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from .models import Stock, Tag
from .forms import *
from django.shortcuts import get_object_or_404
import csv
import datetime
from django.db.models import Q, Sum
from django.template.loader import render_to_string
from django.contrib import messages
from weasyprint import HTML
import tempfile
import xlwt
# Create your views here.


def export_excel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=stock excel' + str(datetime.datetime.now()) + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Stock')
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['NAME', 'QUANTITY', 'QUANTITY RECEIVED']
    for col in range(len(columns)):
        ws.write(row_num, col, columns[col], font_style)
    font_style.font.bold = xlwt.XFStyle()
    rows = Stock.objects.filter().values_list('name', 'quantity', 'receive_quantity')
    for row in rows:
        row_num += 1
        for col in range(len(row)):
            ws.write(row_num, col, str(row[col]), font_style)
    wb.save(response)
    return response


def dashboard(request):
    return render(request, 'sms_app/dashboard.html')


def all_stock(request):
    form = StockSearchForm(request.POST or None)
    stock = Stock.objects.all()
    title = 'Inventory'
    content = 'This page represent all products stocked in our inventory'
    context = {'all_stock': stock, 'title': title, 'content': content, 'form': form}
    if request.method == 'POST':
        stock = Stock.objects.filter(name__icontains=form['name'].value(),
                                     quantity__icontains=form['quantity'].value())
        context = {'all_stock': stock, 'title': title, 'content': content, 'form': form}
        if form['export_to_csv'].value() == True:
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename=list of stock' + str(datetime.datetime.now()) + '.csv'
            writer = csv.writer(response)
            writer.writerow(['NAME', 'QUANTITY', 'QUANTITY RECEIVED', 'QUANTITY ISSUE'])
            instance = stock
            for st in instance:
                writer.writerow([st.name, st.quantity, st.receive_quantity, st.issue_quantity])
            return response
    return render(request, 'sms_app/all_stock.html', context)


def export_pdf(request):
    stock = Stock.objects.all()
    sum = stock.count()
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=stock pdf' + str(datetime.datetime.now()) + '.pdf'
    response['Content-Transfer-Encoding'] = 'binary'

    html_string = render_to_string('sms_app/pdf-output.html', {'stock': stock, 'total': 0})
    html = HTML(string=html_string)
    result = html.write_pdf()
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())
    return response


def name_tag(request):
    tag = Tag.objects.all()
    return render(request, 'sms_app/all_stock.html', {'tags': tag})


def add_stock(request):
    form = StockFormView(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        messages.success(request, 'Product was added with successfully')
        return redirect('/stocks')
    else:
        form = StockFormView(request.POST, request.FILES)
    title = 'Add Item'
    content = "Let's Add an item to your inventory"
    context = {'form': form, 'title': title, 'content': content}
    return render(request, 'sms_app/add_stock.html', context)


def get_stock(request, id):
    try:
        stock = Stock.objects.get(id=id)
    except Stock.DoesNotExist:
        return render(request, 'sms_app/404.html')
    context = {'get_stock': stock}
    return render(request, 'sms_app/get_stock.html', context)


def receive_quantity(request, id):
    queryset = Stock.objects.get(id=id)
    form = StockReceiveQuantityForm(instance=queryset)
    if request.method == 'POST':
        form = StockReceiveQuantityForm(request.POST or None, instance=queryset)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.receive_quantity = instance.receive_quantity
            instance.save()
            receiver_stock_history = StockHistory(
                id=instance.id,
                name=instance.name,
                description=instance.description,
                price=instance.price,
                quantity=instance.quantity,
                receive_quantity=instance.receive_quantity,
                quantity_required=instance.quantity_required,
                issue_quantity=instance.issue_quantity,
                issue_by=instance.issue_by,
                quantity_calc=instance.quantity_calc,
                last_updated=instance.last_updated,
            )
            receiver_stock_history.save()
            messages.success(request, f"Received Successfully  {str(instance.quantity_calc)}  {str(instance.name)}'s now in store")
            return redirect('/stock/'+str(instance.id))
    context = {
        'title': 'Receive',
        'get_stock': queryset,
        'form': form,
        'username': 'Receive by',
    }
    return render(request, 'sms_app/add_stock.html', context)


def quantity_required(request, id):

    queryset = Stock.objects.get(id=id)
    form = StockQuantityRequiredForm(instance=queryset)
    if request.method == 'POST':
        form = StockQuantityRequiredForm(request.POST or None, instance=queryset)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.quantity_required = instance.quantity_required
            instance.save()
            return redirect('/stock/'+str(instance.id))
    context = {
        'title': 'Receive',
        'get_stock': queryset,
        'form': form,
        'username': 'Receive by',
    }
    return render(request, 'sms_app/add_stock.html', context)


def update_stock(request, id):
    query = Stock.objects.get(id=id)
    form = StockUpdateForm(instance=query)
    if request.method == 'POST':
        form = StockUpdateForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product was Updated with successfully')
            return redirect('/stocks')

    context = {'form': form}
    return render(request, 'sms_app/add_stock.html', context)


def delete_stock(request, id):
    query = Stock.objects.get(id=id)
    if request.method == 'POST':
        query.delete()
        messages.success(request, 'Product was deleted with successfully')
        return redirect('/stocks')
    return render(request, 'sms_app/delete_stock.html')


def reorder_level(request, id):
    queryset = Stock.objects.get(id=id)
    form = ReorderLevelForm(request.POST or None, instance=queryset)
    if request.method == "POST":
        if form.is_valid():
            form = ReorderLevelForm(request.POST or None, instance=queryset)
            instance = form.save(commit=False)
            instance.save()
            return redirect('/stocks')
    context = {
        'stock': queryset,
        'form': form,
    }
    return render(request, 'sms_app/add_stock.html', context)

sms_app/templates/sms_app/add_stock.html
{% extends "sms_app/main.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form|crispy:"bootstrap4" }}<br>
<!--    <input type="submit" value="Save"/>-->
    <br>
    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" value="Save" class="btn btn-primary btn-lg btn-block">Submit</button>
    </div>
</form>






{% endblock %}

sms_app/templates/sms_app/all_stock.html
{% extends "sms_app/main.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<!--<div class="container-fluid">-->
<!--    <div class="row mt-4">-->
<!--        <div class="col-lg-3"></div>-->
<!--        <div class="col-lg-6">-->
<!--            {% for stock in all_stock %}-->
<!--            {{ stock.name }} {{ stock.description }} {{ stock.price }} MAD <br><br>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--        <div class="col-lg-3"></div>-->
<!--</div>-->
<!--</div>-->


<!--<div class="container px-4 py-5" id="custom-cards">-->
<!--    <h2 class="pb-2 border-bottom">Inventory</h2>-->

<!--    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">-->
<!--        {% for stock in all_stock %}-->

<!--      <div class="col-lg-4">-->
<!--        <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">-->
<!--          <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">-->
<!--            <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{ stock.name }}</h2>-->
<!--            <ul class="d-flex list-unstyled mt-auto">-->
<!--              <li class="me-auto">-->
<!--                <img src="https://github.com/twbs.png" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">-->
<!--              </li>-->
<!--              <li class="d-flex align-items-center me-3">-->
<!--                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>-->
<!--                <small>Earth</small>-->
<!--              </li>-->
<!--              <li class="d-flex align-items-center">-->
<!--                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>-->
<!--                <small>3d</small>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--</div>-->
<!--    {% endfor %}-->


<!--<div class="container-fluid">-->
<!--<div class="row mt-4">-->
<!--    <div class="col-lg-3"></div>-->
<!--    <div class="col-lg-6"></div>-->
<!--          {% for stock in all_stock %}-->

<!--<div class="album py-4 bg-light">-->
<!--    <div class="container-fluid">-->

<!--        <div class="col-lg-4">-->

<!--          <div class="card shadow-lg">-->
<!--            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" role="img" aria-label="Placeholder: Thumbnail"  focusable="false">-->
<!--                <rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ stock.name }}</text></svg>-->
<!--              {% if stock.image %}-->
<!--            <img src="{{stock.image.url}}" alt="missing pic" class="rounded-circle" height="200" width="220" style="margin-left:35px;">-->
<!--            {% endif %}-->
<!--            <div class="card-body" style="font-family:i; text-align:center;">-->
<!--               <p class="card-text" style="text-align:center; font-family:i;"> {{ stock.name }}</p>-->
<!--              <p class="card-text" style=" font-family:i;">{{ stock.description|truncatewords:'5' }}</p>-->
<!--              <div class="d-flex justify-content-between align-items-center">-->
<!--                  <small class="text-muted">{{stock.date_created|date:"d-m-Y"}}</small>-->
<!--                  <div class="btn-group" style=" margin-left:5px;">-->
<!--                      <button type="button" class="btn btn-sm btn-outline-secondary" >View</button>-->
<!--                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>-->
<!--                  </div>-->
<!--                    <p class="card-text" style="text-align:center; font-family:i; margin-left:15px; margin-top:px;">{{ stock.price|floatformat:0 }} MAD</p>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--    </div>-->
<!--{% endfor %}-->
<!--</div>-->




<!--    <div class="col-lg-3"></div>-->

<!--    </div>-->
<!--</div>-->




<!-- search-->
{% if messages %}
  <ul class="message" style="font-family:i; text-align:center; background-color:skyblue; font-weight:bold;">
    {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

<form method='POST'>
    {% csrf_token %}
    {{ form|crispy }}<br>
    <input type="submit" value="Search"/>
</form>

<a href="{% url 'sms_app:export-pdf' %}" class="btn btn-info" style="margin-top:-60px; margin-left:900px;">Export PDF</a><br>
<a href="{% url 'sms_app:export-excel' %}" class="btn btn-info" style="margin-top:-108px; margin-left:750px;">Export EXCEL</a><br>
<a href="" class="btn btn-info" style="margin-top:-100px; margin-left:500px;">History</a><br>


<table class="table table-striped" style="text-align:center; font-weight:bold; font-family:i;">
  <br>
  <thead>
    <tr class="table-dark">
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Q: Required</th>
      <th scope="col">Q: Received</th>
      <th scope="col">Q: Issue</th>
      <th scope="col">Q: Total</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Order level</th>
      <th scope="col">Update  or Delete</th>
    </tr>
  </thead>
  {% for stock in all_stock %}

  <tbody>
    <tr>
      <th scope="row" style="color:blue;">{{ stock.id }}</th>
      <td>{% if stock.quantity_calc <= stock.reorder_level %}
        <a href="{% url 'sms_app:get_stock' stock.id %}"><span style="color:white;background-color:black;">{{ stock.name }}</span></a>
      {% else %}
        <a href="{% url 'sms_app:get_stock' stock.id %}"><span style="color:black; ">{{ stock.name }}</span></a>
      {% endif %}</td>
      <td>{{ stock.quantity }}</td>
      <td>{{ stock.quantity_required }} </td>
      <td>{{ stock.receive_quantity }} </td>
      <td><span style="color:red;">{{ stock.issue_quantity }}</span> </td>
      <td>{{ stock.quantity_calc }} </td>
      <td>{{ stock.price }} MAD</td>
      <td><a href="{% url 'sms_app:reorder_level' stock.id %}"><span style="color:grey;">{{ stock.reorder_level }}</span></a></td>
      <td><a href="{% url 'sms_app:update_stock' stock.id %}"><span class="iconify" data-icon="dashicons:update-alt" data-inline="false"></span></a>
        <a href="{% url 'sms_app:delete_stock' stock.id %}"><span class="iconify" data-icon="ion:trash" data-inline="false"></span></a></td>
    </tr>
  </tbody>
    {% endfor %}

</table>



<!--<div class="container">-->
<!--  <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">-->
<!--    <div class="col">-->
<!--      <div class="p-3 border bg-light">Row column</div>-->
<!--    </div>-->

<!--  </div>-->
<!--</div>-->
{% endblock %}

sms_app/templates/sms_app/delete_stock.html
{% extends "sms_app/main.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}


<form method="POST">
    {% csrf_token %}
    <h2> Are you sure you want to delete that item ?</h2>

    <input type="submit" class="btn btn-danger" value="Yes"/>
    <a href="/stocks"><div class="btn btn-primary">Cancel</div></a>
</form>


{% endblock %}

sms_app/templates/sms_app/get_stock.html
{% extends "sms_app/main.html" %}
{% load static %}
{% block content %}




{% if messages %}
  <ul class="message" style="font-family:i; text-align:center; background-color:skyblue;">
    {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

<div style="margin-left:600px;">
    <a href="{% url 'sms_app:receive_quantity' get_stock.id %}"><div class="btn btn-info">Edit Receive Quantity</div></a>
    <a href="{% url 'sms_app:quantity_required' get_stock.id %}"><div class="btn btn-info">Edit Quantity Required</div></a>
</div>
<br>
<div class="row mt-4">
    <div class="col-lg-2"></div>
    <div class="col-lg-6">

    </div>
    <div class="col-lg-4">
        Name : {{ get_stock.name}}<br>
        Description : {{ get_stock.description}}<br>
        Price : {{ get_stock.price}}<br>
        Quantity : {{ get_stock.quantity}}<br>
        Quantity Required : {{ get_stock.quantity_required}}<br>
        Receive Quantity : {{ get_stock.receive_quantity}}<br>
        Issue Quantity : {{ get_stock.issue_quantity}}<br>
        Date Created : {{ get_stock.date_created}}<br>
        Last Update : {{ get_stock.last_updated}}<br>
        <br><br>
        <h3 style="font-weight:bold; font-family:i;">Total Quantity : {{ get_stock.quantity_calc}}</h3><br>
    </div>
</div>

{% endblock %}

sms_app/templates/sms_app/main.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Home</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
  <link rel="stylesheet" href="{% static 'css/https _getbootstrap.com_docs_5.0_dist_css_bootstrap.min.css' %}">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }2
      }
    </style>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/https _getbootstrap.com_docs_5.0_examples_navbar-fixed_navbar-top-fixed.css' %}">

  </head>
  <body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/stocks"><span style="font-weight:bold; font-family:i; color:skyblue; margin-left:20px;">INVETORY</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse" style="margin-left:25px;">
      <ul class="navbar-nav me-auto mb-2 mb-md-0" style="font-family:i;">
        {% url 'sms_app:add_stock' as my_view %}
        {% if request.path == my_view %}
        <li class="nav-item" >
          <a class="nav-link active" aria-current="page" href="/stocks">Inventory</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/add/stock">Add Items</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<main class="container">
  <div class="bg-light p-5 rounded">
    <h1 style="font-family:i; font-weight:bold; text-align:center;" class="pb-5 border-bottom">{{title}}</h1><br>
<!--    <p class="lead" style="text-align:center; font-family:i;">{{content}}</p>-->
<!--    <a class="btn btn-lg btn-primary" href="/docs/5.0/components/navbar/" role="button">View navbar docs &raquo;</a>-->
      {% block content %}


      {% endblock %}

  </div>
</main>


<!--    <script src="/docs/5.0/static/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>-->
    <script src="{% static 'js/https _getbootstrap.com_docs_5.0_dist_js_bootstrap.bundle.min.js' %}" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>


  </body>
</html>